#! /usr/bin/env python
from __future__ import division

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Int32, Bool

from diff_drive import controller

class ControllerNode:

    def __init__(self):
        self.controller = controller.Controller()
        self.linearVelocity = 0.0
        self.angularVelocity = 0.0

        self.ultrasound_ok = True
        self.stopping_factor = 0

    def main(self):
        self.leftPub = rospy.Publisher('lwheel_desired_rate',
                                       Int32, queue_size=1)
        self.rightPub = rospy.Publisher('rwheel_desired_rate',
                                        Int32, queue_size=1)

        rospy.init_node('diff_drive_controller')
        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        rospy.Subscriber("cmd_vel", Twist, self.twistCallback)

        rospy.Subscriber("/hardware/ultrasound", Bool, self.ultrasound_cb)

        self.ticksPerMeter = float(rospy.get_param('~ticks_per_meter'))
        self.wheelSeparation = float(rospy.get_param('~wheel_separation'))
        self.maxMotorSpeed = int(rospy.get_param('~max_motor_speed'))
        self.rate = float(rospy.get_param('~rate', 10.0))
        self.timeout = float(rospy.get_param('~timeout', 0.2))

        self.controller.setWheelSeparation(self.wheelSeparation)
        self.controller.setTicksPerMeter(self.ticksPerMeter)
        self.controller.setMaxMotorSpeed(self.maxMotorSpeed)

        rate = rospy.Rate(self.rate)
        self.lastTwistTime = rospy.get_time()
        while not rospy.is_shutdown():
            self.adjust_max_speed()
            self.publish()
            rate.sleep()

    def ultrasound_cb(self, msg):
        if msg.data != self.ultrasound_ok:
            self.ultrasound_ok = msg.data


    def adjust_max_speed(self):
        if not self.ultrasound_ok and self.stopping_factor > 0:
            self.stopping_factor -= 0.1

        elif self.ultrasound_ok and self.stopping_factor < 1:
            self.stopping_factor += 0.1

        if self.stopping_factor < 0:
             self.stopping_factor = 0
        
        elif self.stopping_factor > 1:
             self.stopping_factor = 1

        self.controller.setMaxMotorSpeed(self.maxMotorSpeed*self.stopping_factor)

    def publish(self):
        if rospy.get_time() - self.lastTwistTime < self.timeout:
            speeds = self.controller.getSpeeds(self.linearVelocity,
                                               self.angularVelocity)
            self.leftPub.publish(int(speeds.left))
            self.rightPub.publish(int(speeds.right))
        else:
            self.leftPub.publish(0)
            self.rightPub.publish(0)

    def twistCallback(self, twist):
        self.linearVelocity = twist.linear.x
        self.angularVelocity = twist.angular.z
        self.lastTwistTime = rospy.get_time()

if __name__ == '__main__':
    try:
        node = ControllerNode()
        node.main()
    except rospy.ROSInterruptException:
        pass
